---
cmd:
  - - cmd/*.go
    - "!cmd/*test.go"
deps:
  - - go.mod
docs:
  - - docs/*
    - mkdocs*yml
tests:
  - - cmd/*test.go
tooling:
  - - .github/**/*
    - .goreleaser.yaml
    - .pre-commit-config.yaml
    - scripts/*
