---
archives:
  - builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/mpg.1
    format_overrides:
      - format: zip
        goos: windows
    rlcp: true
before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
    - ./scripts/manpages.sh
brews:
  - description: Mark's Password Generator
    homepage: https://github.com/mcornick/mpg
    install: |-
      bin.install "mpg"
      bash_completion.install "completions/mpg.bash" => "mpg"
      zsh_completion.install "completions/mpg.zsh" => "_mpg"
      fish_completion.install "completions/mpg.fish"
      man1.install "manpages/mpg.1"
    license: MIT
    tap:
      name: homebrew-tap
      owner: mcornick
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/mcornick/mpg/cmd.version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    targets:
      - go_first_class
changelog:
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "^docs:"
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  sort: asc
  use: github
checksum:
  name_template: checksums.txt
docker_manifests:
  - image_templates:
      - ghcr.io/mcornick/mpg:{{ .Tag }}-amd64
      - ghcr.io/mcornick/mpg:{{ .Tag }}-arm64
    name_template: ghcr.io/mcornick/mpg:{{ .Tag }}
  - image_templates:
      - mcornick/mpg:{{ .Tag }}-amd64
      - mcornick/mpg:{{ .Tag }}-arm64
    name_template: mcornick/mpg:{{ .Tag }}
  - image_templates:
      - ghcr.io/mcornick/mpg:{{ .Tag }}-amd64
      - ghcr.io/mcornick/mpg:{{ .Tag }}-arm64
    name_template: ghcr.io/mcornick/mpg:latest
  - image_templates:
      - mcornick/mpg:{{ .Tag }}-amd64
      - mcornick/mpg:{{ .Tag }}-arm64
    name_template: mcornick/mpg:latest
docker_signs:
  - args:
      - sign
      - ${artifact}@${digest}
    artifacts: manifests
    cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    output: true
gomod:
  proxy: true
kos:
  - bare: true
    id: mpg-ghcr
    platforms:
      - linux/amd64
      - linux/arm64
    repository: ghcr.io/mcornick/mpg
    tags:
      - latest
      - "{{.Tag}}"
  - bare: true
    id: mpg-docker
    platforms:
      - linux/amd64
      - linux/arm64
    repository: mcornick/mpg
    tags:
      - latest
      - "{{.Tag}}"
milestones:
  - close: true
nfpms:
  - contents:
      - dst: /usr/share/bash-completion/completions/mpg
        file_info:
          mode: 0644
        src: ./completions/mpg.bash
      - dst: /usr/share/fish/vendor_completions.d/mpg.fish
        file_info:
          mode: 0644
        src: ./completions/mpg.fish
      - dst: /usr/share/zsh/vendor-completions/_mpg
        file_info:
          mode: 0644
        src: ./completions/mpg.zsh
      - dst: /usr/share/man/man1/mpg.1
        file_info:
          mode: 0644
        src: ./manpages/mpg.1
      - dst: /usr/share/doc/mpg/copyright
        file_info:
          mode: 0644
        src: ./LICENSE
    description: Mark's Password Generator
    formats:
      - apk
      - deb
      - rpm
    homepage: https://github.com/mcornick/mpg
    license: MIT
    maintainer: Mark Cornick <mcornick@mcornick.com>
    vendor: Mark Cornick
sboms:
  - artifacts: archive
scoop:
  bucket:
    name: scoop-bucket
    owner: mcornick
  description: Mark's Password Generator
  homepage: https://github.com/mcornick/mpg
  license: MIT
signs:
  - artifacts: checksum
snapshot:
  name_template: "{{ incpatch .Version }}-next"
universal_binaries:
  - replace: true
