---
announce:
  mastodon:
    enabled: true
    server: https://social.lol
archives:
  - builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpage/mpg.1
    format_overrides:
      - format: zip
        goos: windows
    rlcp: true
aurs:
  - description: "Mark's Password Generator"
    git_url: 'ssh://git@github.com/mcornick/mpg-aur.git'
    homepage: "https://mcornick.com/mpg/"
    license: "MIT"
    maintainers:
      - 'Mark Cornick <mcornick@mcornick.com>'
    name: mpg-bin
    package: |-
      install -Dm755 "./mpg" "${pkgdir}/usr/bin/mpg"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/mpg/LICENSE"
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/mpg.bash" "${pkgdir}/usr/share/bash-completion/completions/mpg"
      install -Dm644 "./completions/mpg.zsh" "${pkgdir}/usr/share/zsh/site-functions/_mpg"
      install -Dm644 "./completions/mpg.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/mpg.fish"
      install -Dm644 "./manpage/mpg.1" "${pkgdir}/usr/share/man/man1/mpg.1"
    private_key: '{{ .Env.AUR_KEY }}'
before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
    - ./scripts/manpage.sh
brews:
  - description: Mark's Password Generator
    homepage: https://github.com/mcornick/mpg
    install: |-
      bin.install "mpg"
      bash_completion.install "completions/mpg.bash" => "mpg"
      zsh_completion.install "completions/mpg.zsh" => "_mpg"
      fish_completion.install "completions/mpg.fish"
      man1.install "manpage/mpg.1"
    license: MIT
    tap:
      name: homebrew-tap
      owner: mcornick
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/mcornick/mpg/cmd.version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    targets:
      - go_first_class
changelog:
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "^docs:"
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  sort: asc
  use: github
checksum:
  name_template: checksums.txt
furies:
  - account: mcornick
gomod:
  proxy: true
kos:
  - bare: true
    build: mpg
    id: mpg-ghcr
    platforms:
      - linux/amd64
      - linux/arm64
    repository: ghcr.io/mcornick/mpg
    tags:
      - latest
      - "{{.Tag}}"
  - bare: true
    build: mpg
    id: mpg-docker
    platforms:
      - linux/amd64
      - linux/arm64
    repository: mcornick/mpg
    tags:
      - latest
      - "{{.Tag}}"
milestones:
  - close: true
nfpms:
  - archlinux:
      packager: Mark Cornick <mcornick@mcornick.com>
    contents:
      - dst: /usr/share/bash-completion/completions/mpg
        file_info:
          mode: 0644
        src: ./completions/mpg.bash
      - dst: /usr/share/fish/vendor_completions.d/mpg.fish
        file_info:
          mode: 0644
        src: ./completions/mpg.fish
      - dst: /usr/share/zsh/vendor-completions/_mpg
        file_info:
          mode: 0644
        src: ./completions/mpg.zsh
      - dst: /usr/share/man/man1/mpg.1
        file_info:
          mode: 0644
        src: ./manpage/mpg.1
      - dst: /usr/share/doc/mpg/copyright
        file_info:
          mode: 0644
        src: ./LICENSE
    description: Mark's Password Generator
    formats:
      - apk
      - archlinux
      - deb
      - rpm
    homepage: https://github.com/mcornick/mpg
    license: MIT
    maintainer: Mark Cornick <mcornick@mcornick.com>
    vendor: Mark Cornick
sboms:
  - artifacts: archive
scoop:
  bucket:
    name: scoop-bucket
    owner: mcornick
  description: Mark's Password Generator
  homepage: https://github.com/mcornick/mpg
  license: MIT
signs:
  - artifacts: checksum
snapshot:
  name_template: "{{ incpatch .Version }}-next"
universal_binaries:
  - replace: true
# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
