---
repos:
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.0
  - hooks:
      - id: golangci-lint-mod
    repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.4
