---
copyright: Copyright &copy; 2023 Mark Cornick
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
repo_name: mcornick/mpg
repo_url: https://github.com/mcornick/mpg
site_author: Mark Cornick
site_description:
  mpg is a command-line tool that generates strings of random characters
  that can be used as reasonably secure passwords.
site_name: "mpg: Mark's Password Generator"
theme:
  features:
    - content.action.edit
    - content.action.view
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
