---
copyright: Copyright &copy; 2023 Mark Cornick
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Contributing: contributing.md
repo_url: https://github.com/markcornick/mpg/
site_author: Mark Cornick
site_description: "Mark's Password Generator"
site_name: mpg
theme: readthedocs
