---
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version: ">=1.19.5"
      - uses: sigstore/cosign-installer@main
        with:
          cosign-release: v1.2.1
      - uses: anchore/sbom-action/download-syft@main
        with:
          syft-version: v0.69.0
      - id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: echo "$GPG_PRIVATE_KEY" > /home/runner/gpgkey.asc && chmod 600 /home/runner/gpgkey.asc
        shell: bash
      - env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        run: echo "$COSIGN_PRIVATE_KEY" > /home/runner/cosign.asc && chmod 600 /home/runner/cosign.asc
        shell: bash
      - uses: docker/login-action@v2
        with:
          password: ${{ secrets.GH_PAT }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
      - env:
          COSIGN_KEY_PATH: /home/runner/cosign.asc
          COSIGN_PWD: ${{ secrets.COSIGN_PWD }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GPG_KEY_PATH: /home/runner/gpgkey.asc
          NFPM_DEFAULT_PASSPHRASE: ${{ secrets.PASSPHRASE }}
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
          distribution: goreleaser
          version: latest
      - run: rm /home/runner/gpgkey.asc /home/runner/cosign.asc
        shell: bash
name: goreleaser
"on":
  push:
    tags:
      - "*"
permissions:
  contents: write
  issues: write
  packages: write
